### ISSUE TITLE
The post example has a bug!

### ISSUE THREAD

**Issue by ghost** [oatpp/oatpp-examples#5]
The post param as:

> 
{"id": 1,"first-name": "xxxxx","last-name": "xxxxx","friends": ["xxxxx"]}

> 

but response:

> 
server=oatpp/0.18.9
code=400
description=Bad Request
message=Missing valid body parameter 'userDto'

>

**Comment by ghost** [comment]
I konw!
The bug is cannot remote post!
only suppert localhost!

**Comment by lganzzzo** [comment]
Thank you for the issue.

Please provide full curl request.
Also please check if swagger works for you. SwaggerUi is at ```http://<host>:<port>/swagger/ui```

Thank you

**Comment by ghost** [comment]
I just try a moment!
The postman cannot support!
The command tools "curl" is ok!

Ths Swagger UI cannot execute,
I think the reason is host,
this demo is running my remote server,but the host still localhost

**Comment by lganzzzo** [comment]
In order to make swagger work correctly for your remote host change swagger host in SwaggerComponent.hpp  

File:
https://github.com/oatpp/oatpp-examples/blob/master/crud/src/SwaggerComponent.hpp

``` .addServer("<your-remote-host>", "<description>"); ```

It should be pointing to your remote

**Comment by ghost** [comment]
Ok! 
I find out this bug!
Reason from a wrong method!
The example is 'POST',
But when I press the execute button,the request was ‘OPTIONS’;

**Comment by lganzzzo** [comment]
Okay, I hope you managed to make it work!

Best Wishes
Leonid
