### ISSUE TITLE
in WSL, run get Aborted

### ISSUE THREAD

**Issue by lmj01** [oatpp/oatpp-examples#6]
terminate called after throwing an instance of 'std::runtime_error'
what(): Can't bind to address
Aborted(core dumped)

not add the component for server, it's ok, but add the compont on the step-by-step, get the wrong

**Comment by lganzzzo** [comment]
It is a known issue. Can't bind to address in WSL.

See https://github.com/oatpp/oatpp/issues/22 

I'l update this issue once resolution is found
