### ISSUE TITLE
Need an example for parsing received JSON body

### ISSUE THREAD

**Issue by puneetugru** [oatpp/oatpp-examples#7]
Hi Leonid,

I've a requirement to parse received JSON body.

My DTO is as below,
```cpp
class DataDto : public oatpp::data::mapping::type::Object {

  DTO_INIT(DataDto, Object /* Extends */)

  DTO_FIELD(Float32, temperature);   // temperature code field
  DTO_FIELD(Int64, timestamp);     // timestamp field

};
```
My controller is as below,

```cpp
ENDPOINT("POST", "{path-param}/temperature", getTemperature,
           REQUEST(std::shared_ptr<IncomingRequest>, request), // Map request object to endpoint method
           PATH(String, pathParam, "path-param"),
           BODY_DTO(DataDto::ObjectWrapper, DataDto)) {
    
    OATPP_LOGI("App", "Received call-back for temperature");
    /* return result */
    return createResponse(Status::CODE_200, "path-param=" + pathParam);
    
  } 
```

Although I see that the controller gets called properly and I'm able to send response with CODE_200, I did not find example to parse the body and get the output.

**Comment by lganzzzo** [comment]
Hello @puneetugru !

use `dataDto->temperature`, `dataDto->timestamp` to access the fields

```cpp
  ENDPOINT("POST", "{path-param}/temperature", getTemperature,
           PATH(String, pathParam, "path-param"),
           BODY_DTO(DataDto::ObjectWrapper, dataDto)) {

    

    OATPP_LOGI("App", "Received call-back for temperature=%f", dataDto->temperature ->getValue());
    /* return result */
    return createResponse(Status::CODE_200, "path-param=" + pathParam);
    
  } 
```
Also see some more examples here:
https://github.com/oatpp/oatpp#post-json-body

Regards,
Leonid

**Comment by puneetugru** [comment]
Thank you for your response.
I tried to print both timestamp and temperature, but I see that temperature value is getting printed twice.
My code is as below,

```cpp
ENDPOINT("POST", "{path-param}/temperature", getTemperature,
           REQUEST(std::shared_ptr<IncomingRequest>, request), // Map request object to endpoint method
           PATH(String, pathParam, "path-param"),
           BODY_DTO(DataDto::ObjectWrapper, dataDto)) {


    OATPP_LOGI("MyApp", "Received value for temperature=%lf", dataDto->temperature->getValue());
    OATPP_LOGI("MyApp", "Received value for timestamp=%lf", dataDto->timestamp->getValue());
    /* return result */
    return createResponse(Status::CODE_200, "path-param=" + pathParam);

  }
```
Output is as below,

I |2019-07-31 06:49:24 1564535964257033| MyApp:Received value for temperature=38.000000
 I |2019-07-31 06:49:24 1564535964257075| MyApp:Received value for timestamp=38.000000
 I |2019-07-31 06:49:25 1564535965260690| MyApp:Received value for temperature=1.000000
 I |2019-07-31 06:49:25 1564535965260740| MyApp:Received value for timestamp=1.000000

**Comment by lganzzzo** [comment]
Hey @puneetugru ,

I have it reproduced. Seems like this is a bug.
I will investigate this and inform you on the progress!

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Hey @puneetugru ,

I found that issue was in incorrect logging.
The dto object has all of its fields with correct values.

You have to use `%d` for Int64 values.

The correct code is:
```cpp
  ENDPOINT("POST", "{path-param}/temperature", getTemperature,
           REQUEST(std::shared_ptr<IncomingRequest>, request), // Map request object to endpoint method
           PATH(String, pathParam, "path-param"),
           BODY_DTO(DataDto::ObjectWrapper, dataDto)) {


    OATPP_LOGI("MyApp", "Received value for temperature=%lf", dataDto->temperature->getValue());
    OATPP_LOGI("MyApp", "Received value for timestamp=%d", dataDto->timestamp->getValue());
    /* return result */
    return createResponse(Status::CODE_200, "path-param=" + pathParam);

  }
```

**Comment by puneetugru** [comment]
Hi Leonid,

Thank you for the update.

I've rectified my code.

So, is it like the getValue() is also dependent on the type of the variable in DTO?

**Comment by lganzzzo** [comment]
Hello @puneetugru ,

Yes, in your `DataDto`:

`temperature->getValue()` - is float value
`timestamp->getValue()` - is int64 value

Regards,
Leonid

**Comment by puneetugru** [comment]
Hi Leonid,

So, can we keep two values having same data type in DTO?

Also, I guess currently there is no support for array as part of DTO, right?

Thanks,
Puneet

**Comment by lganzzzo** [comment]
Hey @puneetugru ,

DTO objects have full support of json features.

Please find full usage example here: https://oatpp.io/docs/components/dto/

Best Regards,
Leonid

**Comment by puneetugru** [comment]
Hi Leonid,

Pardon my ignorance. 
I'll go through the documentation more diligently.

Thanks,
Puneet

**Comment by lganzzzo** [comment]
@puneetugru 

Please let me know in case of any questions
